config/routes.rb
Rails.application.routes.draw do



  get '/routines/index' => 'routines#index'
  root 'page#homepage'
  post '/users' => 'page#user_create'
  post '/login' => 'sessions#create'

  get '/personalize' => 'users#personalize'
  post '/personalize' => 'users#personalized'
  get '/equipment' => 'users#equipment'
  post '/equipment' => 'users#equipmentd'
  get '/dashboard' => 'dashboard#dashboard', as: 'dashboard'
  get '/settings' => 'dashboard#settings'
  get '/logout' => 'sessions#destroy'
  post '/update' => 'users#update'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def dashboard
    @user = current_user
  end
  def settings
    @user = current_user
    @routine_trackers = @user.routine_trackers.reverse
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/dashboard.html.erb
<!-- <h1>dashboard</h1>
<%= @user.name%> -->
<div class="main-dashboard-container">

  <div class="top-nav-bar-container">
    <%= link_to image_tag("https://s3.amazonaws.com/fit-pngs/Profile_icon.png", :style => 'height: 8vh; margin-right: 1vh;', id: "profile-icon"), settings_path%>
    <!-- <img src="https://s3.amazonaws.com/fit-pngs/Profile_icon.png" id="profile-icon" alt="Picture of Profile Icon" /> -->
  </div>

  <div class="greeting-container">
    <h3 id="greeting" >Hello, <%= @user.name%></h3>
  </div>
  <div class="last-workouts-container">
    <div class="smaller-inner-div"><div id="last-workouts-h6-container"><h6 id="last-workouts">Last workouts</h6></div></div>
    <div class="bigger-inner-div" id="column-header-container"><div class="column-header"><h6 class="header-content">Date</h6></div><div class="column-header"><h6 class="header-content">Routine</h6></div><div class="column-header"><h6 class="header-content">Time</h6></div></div>
    <div class="bigger-inner-div" id="last-workout-slot-one"><div class="column-header"><h6 class="header-content" id="last-workout-slot-one-col-one">Date</h6></div><div class="column-header"><h6 class="header-content" id="last-workout-slot-one-col-two">Date</h6></div><div class="column-header"><h6 class="header-content" id="last-workout-slot-one-col-three">Date</h6></div></div>
    <div class="bigger-inner-div" id="last-workout-slot-two"><div class="column-header"><h6 class="header-content" id="last-workout-slot-two-col-one">Date</h6></div><div class="column-header"><h6 class="header-content" id="last-workout-slot-two-col-two">Date</h6></div><div class="column-header"><h6 class="header-content" id="last-workout-slot-two-col-three">Date</h6></div></div>
    <div class="bigger-inner-div" id="last-workout-slot-three"><div class="column-header"><h6 class="header-content" id="last-workout-slot-three-col-one">Date</h6></div><div class="column-header"><h6 class="header-content" id="last-workout-slot-three-col-two">Date</h6></div><div class="column-header"><h6 class="header-content" id="last-workout-slot-three-col-three">Date</h6></div></div>
  </div>
  <div class="start-workout-button-container">
    <img id="start-workout-button" src="https://s3.amazonaws.com/fit-pngs/Put+in+Work+button.png" alt="Start workout icon" />
  </div>
</div>

app/views/dashboard/settings.html.erb
<div class="settings-main-container">
  <%= button_to "Back", dashboard_path, id: 'settings-back-button', method: 'get' %>

  <div class="middle-settings-container">
      <%= form_tag "/update", method: "post", id: "update-personal-form", remote: true do %>
        <div class="jus-a-lil-space-yo"></div>
        <div class="settings-name-container">
          <div class="inner-inner-setting-container"><span id="name-settings-span">Name:</span></div> <%= text_field_tag :name, nil, placeholder: @user.name, class: "name-input-settings-field", id: "name-field-settings" %>
        </div>
        <div class="settings-gender-container">
          <div class="gender-inner-inner-container">
            <%= check_box_tag :male, "1", @user.male?, class: "male-check-box-settings"%><span id="male-check-box-span">Male</span>
          </div>
          <div class="gender-inner-inner-container">
            <%= check_box_tag :female,  "1", @user.female?, class: "female-check-box-settings"%><span id="female-check-box-span">Female</span>
          </div>
        </div>
        <div class="settings-age-container">
          <div class="inner-inner-setting-container"><span id="age-setting-span">Age:</span></div> <%= text_field_tag :age, nil, placeholder: @user.age, class: "age-input-settings-field", id: "age-field-settings" %>
        </div>
        <div class="settings-height-input-container">
          <div class="inner-inner-setting-container"><span id="setting-height-span">Height:</span></div>
          <div class="inner-right-height-container">
            <%= text_field_tag :height_ft, nil, placeholder: @user.height_ft, class: "height-ft-input-settings-field", id: "height-ft-field-settings" %><span id="setting-feet-span">ft</span>
            <%= text_field_tag :height_in, nil, placeholder: @user.height_in, class: "height-in-input-settings-field", id: "height-in-field-settings" %> <span id="setting-inches-span">in</span>
          </div>
        </div>
        <div class="settings-weight-input-container">
          <div class="inner-inner-setting-container"><span id="setting-weight-span">Weight:</span></div> <%= text_field_tag :weight, nil, placeholder: @user.weight, class: "weight-input-settings-field", id: "weight-field-settings" %>
        </div>
        <div class="setting-update-submit-button-container">
          <%= submit_tag "Update", class: "settings-update-submit-button", id: "update-submit-button" %>
        </div>
      <%end%>
  </div>



  <%= button_to "Logout", logout_path, id: 'logout-button', method: 'get' %>
</div>